BlogAPI/urls.py
from django.contrib import admin
from django.urls import path, include

#  
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500, handler400, handler403
from main import views as main_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('main.urls', 'main'), namespace="main")),
    path('', include(('accounts.urls', 'accounts'), namespace="accounts")),
    path('posts/', include(('post.urls','post'), namespace="posts")),
    path('api-auth/', include('rest_framework.urls')),
    path('api/posts/', include('post.api.urls', namespace="post-api"))
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# Defining the new error handlers
handler400 = main_views.error400
handler403 = main_views.error403
handler404 = main_views.error404
handler500 = main_views.error500

admin.site.site_header = "mPharma Adminstration"
admin.site.site_title = "mPharma Adminstration"

accounts/urls.py
from django.urls import path
from . import views

app_name="accounts"

urlpatterns = [
	path('signup', views.signup, name='signup'),
	path('login', views.login_view, name='login'),
	path('userlist', views.user_list, name='user_list'),
	path('profile', views.self_profile, name='self_profile'),
	path('profile/update', views.self_profile, name='update_profile'),
	path('u/<username>', views.public_profile, name='profile'),
	path('logout', views.logout_view, name='logout_view'),
	path('u/<username>/follow', views.follow, name='follow'),
	]

main/urls.py
from django.urls import path
from . import views

app_name="main"

urlpatterns = [
	path('', views.index, name="index"),
	]

post/urls.py
from django.urls import path
from . import views

app_name="post"

urlpatterns = [
	path('create/', views.post_create, name="create"),
    path('<slug:slug>/', views.post_view, name="post_view"),
]

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title>mPharma | Blog</title>
</head>
<body>
	<!-- <link rel="stylesheet" type="text/css" href=""> -->
	<h1><a href="{% url 'main:index' %}">mPharma</a></h1>
	<p><a href="{% url 'accounts:self_profile' %}">{{current_user}}</a></p>
	{% if user.is_authenticated %}
		<a href="{% url 'accounts:logout_view' %}">Logout</a>
		<a href="{% url 'accounts:user_list' %}"> User List </a>
	{% else %}
		<a href="{% url 'accounts:signup'%}">SignUp</a>/<a href="{% url 'accounts:login' %}">LogIn</a>
	{% endif %}
	{% block content %}
	<h3>Below is the list of all the posts:</h3>
	{% for instance in queryset %}
		<a href="{{instance.get_absolute_url}}">{{instance.heading}}</a></br>
	{% endfor %}
	<h3>You can create your post too -- </h3>
	<a href="{% url 'posts:create'%}">Create</a>
	{% endblock %}

	<h3>Following</h3>
	{% for x in request.user.profile.get_following %}
		<p>{{ x.user.username }}</p>
		{% empty %}
		<p>Not following anyone.</p>
	{% endfor %}
	<hr/>
	<h3>Followed By</h3>
	{% for x in request.user.profile.followed_by.all %}
		<p>{{ x.user.username }}</p>
		{% empty %}
		<p>Not followed anyone.</p>
	{% endfor %}
</body>
</html>